[package]
name = "veloce"
version = "0.1.0"
edition = "2021"
authors = ["Jian Chen <admin@chensoft.com>"]
license = "MIT"
description = "Fast and Powerful HTTP router written in Rust"
documentation = "https://docs.rs/veloce"
repository = "https://github.com/chensoft/veloce"
readme = "README.md"
keywords = ["veloce", "http", "router", "web", "server"]

[dependencies]
mime = "0.3"
http = { package = "hyper", version = "0.14", features = ["full"] }
tokio = { version = "1.35", features = ["full"] }
anyhow = { version = "1.0", features = ["backtrace"] }
logkit = "0.3"
chrono = "0.4"
futures = "0.3"
indexmap = "2.2"
thiserror = "1.0"
async-trait = "0.1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "server"
harness = false
